name: identity_voting_experiment
channels:
  - conda-forge
  - plotly
  - r

dependencies:
  - conda-build
  - ipykernel
  - jupyterlab
  - plotly>=5.5.0
  - pandas
  - pip
  - pytask>=0.0.14
  - pytask-latex>=0.0.12
  - pytask-r>=0.0.9
  - pytest
  - pytest-cov
  - python=3.9
  - python-graphviz

  - pip:

    - pre-commit
    - otree
    - kaleido
    - sphinx
    - sphinx-autobuild
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
    - sphinxcontrib.bibtex
    - sqlalchemy==1.3.22
    - matplotlib
    - django-crispy-forms